name       : python-build
version    : 1.0.3
release    : 5
source     :
    - https://github.com/pypa/build/archive/refs/tags/1.0.3.tar.gz : 4f9201228d0af78aac3c672e89a81749a001d8d7f448cf9196d93cce8d5ee45a
homepage   : https://github.com/pypa/build
license    : MIT
component  : programming.python
summary    : A simple, correct PEP 517 build frontend
description: |
    A simple, correct PEP 517 build frontend. python-build will invoke the PEP 517 hooks to build a distribution package. It is a simple build tool and does not perform any dependency management.
builddeps  :
    - python-build
    - python-flit-core
    - python-installer
    - python-packaging
rundeps    :
    - python-packaging
    - python-pyproject-hooks
build      : |
    %python3_setup
install    : |
    %python3_install
