name       : python-build
version    : 0.9.0
release    : 4
source     :
    - https://github.com/pypa/build/archive/refs/tags/0.9.0.tar.gz : 6eac514275e6a6e6c88373cc536a8eefa446ad6260567ec6ee367519447d382b
homepage   : https://github.com/pypa/build
license    : MIT
component  : programming.python
summary    : A simple, correct PEP 517 build frontend
description: |
    A simple, correct PEP 517 build frontend. python-build will invoke the PEP 517 hooks to build a distribution package. It is a simple build tool and does not perform any dependency management.
rundeps    :
    - python-pep517
    - python-tomli
build      : |
    %python3_setup
install    : |
    %python3_install
