name       : python-build
version    : 0.7.0
release    : 1
source     :
    - https://github.com/pypa/build/archive/refs/tags/0.7.0.tar.gz : 1f1a52767a0b92b37e53eb1fa6017b3d08fddf99e3341a37d2535bc03177b243
homepage   : https://github.com/pypa/build
license    : MIT
component  : programming.python
summary    : A simple, correct PEP 517 build frontend
description: |
    A simple, correct PEP 517 build frontend. python-build will invoke the PEP 517 hooks to build a distribution package. It is a simple build tool and does not perform any dependency management.
rundeps    :
    - python-pep517
    - python-tomli
build      : |
    %python3_setup
install    : |
    %python3_install
